apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-color
  labels:
    app: webapp-color
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp-color
  template:
    metadata:
      labels:
        app: webapp-color
    spec:
      containers:
      - name: webapp-color
        image: kodekloud/webapp-color
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-color
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-name: "test-alb"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "false" # Ensure this line is not set to "true"
spec:
  type: LoadBalancer
  selector:
    app: webapp-color
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080