apiVersion: apps/v1
kind: Deployment
metadata:
  name: valid-deployment
  namespace: default
  labels:
    inventory: "weapons"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80