apiVersion: v1
kind: Pod
metadata:
  name: lifecycle-demo-pod
  labels:
    app: demo
spec:
  containers:
  - name: lifecycle-demo-container
    image: nginx:latest
    
    # Defining the lifecycle hooks
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh", "-c", "echo 'Hello from the postStart handler' > /usr/share/nginx/html/index.html"]
      
      preStop:
        exec:
          command: ["/bin/sh", "-c", "nginx -s quit; while killall -0 nginx; do sleep 1; done"]
          
    ports:
    - containerPort: 80